#Swagger UI configuration
quarkus.swagger-ui.always-include=true

#DB configuration
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/productdb
quarkus.hibernate-orm.database.generation=update

#CORS
quarkus.http.cors=true
quarkus.http.cors.enabled=true 
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization